export const libros = [
  {
    id: "1",
    title: "De Los pies a La Cabeza. Mi 1er Vocabulario Flamenco",
    description:
      "Un álbum imprescindible para descubrir mediante pegadizas rimas el significado de estas quince palabras tan flamencas: abanico, bata de cola, cante jondo, cajón, castañuelas, compás, duende, fiesta, flores, guitarra, jaleos, palmas, palos, tablao, zapatear. Un divertido curso de flamenco básico en verso y a todo color: ¿quieres aprender a tocar las palmas?, ¿sabes si tienes duende?, ¿cómo suenan las castañuelas?, ¿cuál es el origen del cajón? Un regalo para todas las pequeñas flamencas y flamencos de corazón (aunque algunos aún no sepan que lo son).",
    image: "/images/libros/libro1.webp",
    year: 2019,
    author: "Montse Ganges",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
  {
    id: "2",
    title: "¿Cómo se llaman las niñas flamencas?",
    description:
      "Las Niñas Flamencas tienen nombres que suenan a palmas, secretos, olas, truenos, taconeo, cascabeles, risas, susurros, lluvia, fiesta... Las Niñas Flamencas se llaman como son. ¿Y tú? ¡Conócelas e inventa tu nombre flamenco!",
    image: "/images/libros/libro2.webp",
    year: 2013,
    author: "Montse Ganges",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
  {
    id: "3",
    title: "¿De qué están hechas las niñas flamencas?",
    description:
      "Las niñas flamencas viven en un mundo de lunares y flores, de alegrías y colores, de corazones y ¡oles! Descubre el duende del flamenco de la mano de sus singulares protagonistas, las niñas flamencas, en este festival pop-up lleno de arte, humor y poesía. Incluye un tablao flamenco y las muñecas de las niñas flamencas.",
    image: "/images/libros/libro3.webp",
    year: 2011,
    author: "Montse Ganges",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
  {
    id: "4",
    title: "Lola Flores ¿Cómo me las maravillaría yo?",
    description:
      "¿Cómo me las maravillaría yo? es un paseo poético y colorista, por la vida de Lola Flores; primera protagonista de la colección “Flamencas Fantásticas”, dedicada a Mujeres en la historia del Flamenco. Podrás conocer sus aventuras a través de Rimas divertidas, colores brillantes, juegos y ejercicios didácticos.",
    image: "/images/libros/libro4.webp",
    year: 2022,
    author: "Almudena Navarro",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
  {
    id: "5",
    title: "Currita Nuñez. Una lagartija muy flamenca",
    description:
      "Currita Núñez es una lagartija con mucho arte y salero, pero un día sucede algo que le hace cambiar por completo el compás de su vida? ¿Será Currita capaz de recuperar lo que la hace única?",
    image: "/images/libros/libro5.webp",
    year: 2025,
    author: "Almudena Navarro, Rocío Moreno",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
  {
    id: "6",
    title: "Flamenco y rumba desde Cataluña",
    description:
      'Es un viaje de ida y vuelta, un recorrido por el mundo Flamenco/ Rumbero que desde Cataluña ha llegado a enamorar al mundo entero. Un álbum ilustrado para descubrir, conocer y reconocer algunos de los más importantes. "Cantaores", "bailaores" y "guitarristas" que ha dado Cataluña. Doce personajes, doce notas y doce colores para que aprendas de una manera divertida a reconocer a nuestros Artistas! ¡¡¡¡un aplauso para ellos!!!! ¡ole!',
    image: "/images/libros/libro6.webp",
    year: 2020,
    author: "Susana Subirana",
    illustrator: "Susana Subirana",
    hasAnimation: false,
  },
];

export const carteles = [
  {
    id: "1",
    title: "Belleza en extinción",
    description:
      "Portada núm.45 del proyecto Masnounien homenaje a la revista The New Yorker",
    image: "/images/carteles/cartel1.webp",
    year: 2025,
  },
  {
    id: "2",
    title: "Mas Now",
    description:
      "Portada núm.13 del proyecto Masnounien homenaje a la revista The New Yorker",
    image: "/images/carteles/cartel2.webp",
    year: 2025,
  },
  {
    id: "3",
    title: `Exposición de "Flamencas Ilustradas"`,
    description:
      "Exposición en Jerez de la Frontera de fotografías ilustradas. Imagen fotográfica a cargo de Isa de la Calle y ilustraciones y grafismo de Susana Subirana",
    image: "/images/carteles/cartel3.webp",
    year: 2022,
  },
  {
    id: "4",
    title: `Cartel para el Festival Internacional "Kriatura" de Flamenco infantil y juvenil (Dinamarca-Jerez)`,
    description: "",
    image: "/images/carteles/cartel4.webp",
    year: 2024,
  },
  {
    id: "5",
    title: `Cartel para el Festival Internacional "Kriatura" de Flamenco para niños (Dinamarca-Jerez)`,
    description: "",
    image: "/images/carteles/cartel5.webp",
    year: 2021,
  },
  {
    id: "6",
    title: `Cartel para el Festival Internacional "Kriatura" de Flamenco para niños (Dinamarca-Jerez)`,
    description: "Échale papa",
    image: "/images/carteles/cartel9.webp",
    year: 2026,
  },
  {
    id: "7",
    title: "Festival FlamencGi (Girona)",
    description: "",
    image: "/images/carteles/cartel7.webp",
    year: 2022,
  },
  {
    id: "8",
    title: `Espectáculo "LOLA, Flamenco direct from Jerez"`,
    description: "Little Big Festival en Glastonbury (Reino Unido)",
    image: "/images/carteles/cartel8.webp",
    year: 2022,
  },
  {
    id: "9",
    title: `Portada de revista`,
    description: "",
    image: "/images/carteles/cartel9.webp",
    year: 2026,
  },
  {
    id: "10",
    title: `Cartel II Feria Solidaria`,
    description: "Sevillanas por un NIÑO",
    image: "/images/carteles/cartel10.webp",
    year: 2026,
  },
  {
    id: "11",
    title: `Portada álbum "Opus II"`,
    description: "Candela y lo demás",
    image: "/images/carteles/cartel11.webp",
    year: 2025,
  },
  {
    id: "12",
    title: `Portada sencillo "Cercanias"`,
    description: "Candela y lo demás",
    image: "/images/carteles/cartel12.webp",
    year: 2025,
  },
];

export const proyectos = [
  {
    id: "1",
    title: `"WA", Armonía y equilibrio entre fuerzas opuestas`,
    description:
      "Trabajo realizado para la clínica Mi Tres Torres de Barcelona. Serie de ilustraciones inspiradas en conceptos sanadores de la filosofía tradicional japonesa.",
    year: 2026,
    hasAnimation: false,
  },
  {
    id: "2",
    title: "Flamencas Ilustradas",
    description:
      "FLAMENCAS ILUSTRADAS es un proyecto colaborativo entre dos artistas, es Arte sobre Arte. Colección de mujeres flamencas en Blanco y negro con fotografías de Isa de Calle e ilustración de Susana Subirana. Copias en venta disponibles en la tienda.",
    year: 2022,
    hasAnimation: false,
  },
  {
    id: "3",
    title: "Guzzo",
    description: "Postales para el restaurante Guzzo Club de Barcelona.",
    year: 2016,
    hasAnimation: false,
  },
  {
    id: "4",
    title: "Diari ARA",
    description: `Ilustraciones para el diario "Ara" de Barcelona. Serie de ilustraciones para la sección de cultura del diario.`,
    year: 2014,
    hasAnimation: false,
  },
  {
    id: "5",
    title: "Churro",
    description: "Estampación de una furgoneta ambulante de Xurreries Montse.",
    year: 2021,
    hasAnimation: false,
  },
  {
    id: "6",
    title: "Retratos Animaloides",
    description:
      "Retratos ilustrados de animales de compañía. Contacta conmigo si quieres un retrato personalizado de tu mascota.",
    year: 2022,
    hasAnimation: true,
  },
  {
    id: "7",
    title: "MaLaMar",
    description: `Montaje  que escenifica el impulso necesario para ir contra corriente, para navegar contra el viento, para encontrar la calma después de la tormenta. Es una “performance” que mezcla ilustración proyectada, efectos de luces y sombras, baile flamenco, música y efectos de sonido.`,
    year: 2022,
    hasAnimation: false,
  },
];

export const animaciones = [
  {
    id: "1",
    title: "MaLaMar",
    description: `Montaje  que escenifica el impulso necesario para ir contra corriente, para navegar contra el viento, para encontrar la calma después de la tormenta. Es una “performance” que mezcla ilustración proyectada, efectos de luces y sombras, baile flamenco, música y efectos de sonido.`,
    image: "/images/animaciones/MaLaMar.mp4",
    hasAnimation: true,
    year: 2022,
  },
];

export const obras = [
  {
    id: "1",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "La Fabi",
    description:
      "Fabiola Pérez (Arcos de la Frontera), más conocida como La Fabi, es una cantaora que ha cantado para grandes figuras del baile y se desenvuelve a la perfección en los cantes de compás. Ha trabajado en la compañía de Cristina Hoyos y ha compartido escenario con artistas como Farruquito, Farru y Antonio Canales, entre otros.",
    image: "/images/obras/LaFabi.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "2",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Ana Crismán",
    description:
      "Ana Crismán, nacida en Jerez de la Frontera (Cádiz), es la primera y la única persona a nivel mundial que interpreta y compone flamenco con arpa. Exótica en el mundo musical y también en el flamenco, esta artista es absolutamente única y exclusiva en el mundo entero.",
    image: "/images/obras/AnaCrisman.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "3",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Gema Moneo",
    description:
      "Gema Moneo (Jerez de la Frontera) es una bailaora flamenca, reconocida por su temperamento explosivo y su técnica excepcional, combina el purismo de su herencia gitana con influencias modernas de grandes maestros. Se ha consolidado como uno de los máximos exponentes de la escuela del baile jerezano, combinando fuerza, elegancia y un uso muy expresivo de los brazos.",
    image: "/images/obras/GemaMoneo.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "4",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Sofía del Río",
    description:
      "Sofía del Río es una destacada bailaora de flamenco madrileña con gran arraigo en Jerez. Es ampliamente conocida por sus actuaciones en escenarios emblemáticos y por ser la fundadora de La Soleá Flamenco, un centro dedicado a la enseñanza y divulgación de este arte. Conocida por su gran versatilidad y fuerza sobre el escenario, aportando elegancia y un marcado compás jerezano.",
    image: "/images/obras/SofiaDelRio.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "5",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Pastora Galván",
    description:
      "Pastora Galván es una destacada bailaora flamenca nacida en Sevilla. Hija de José Galván, Pastora lleva en su sangre la solera de los bailes de su casa y la modernidad de la danza de su hermano Israel Galván, un genio a la vanguardia más plausible del flamenco.",
    image: "/images/obras/PastoraGalvan.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "6",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "María del Tango",
    description:
      "María del Tango (Caniles) es cantante y músico, aficionada al flamenco. Comenzó su trayectoria musical a una edad temprana, cantando saetas en su ciudad natal. Se trasladó a Granada, donde se profesionalizó y comenzó a componer música para actuaciones callejeras y tablaos. Actualmente, está inmersa en su proyecto en solitario “Entre Dos Mundos”, donde explora la dualidad entre el flamenco tradicional y sonidos contemporáneos.",
    image: "/images/obras/MariaDelTango.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "7",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Mercedes Ruiz",
    description:
      "Mercedes Ruiz (Jerez de la Frontera) ha sido coreógrafa del Ballet Nacional de España y realiza una labor intensa y continua como maestra internacional de baile flamenco. Mercedes respira en flamenco, siente a través del flamenco, es una forma de pensar, de sentir, de vivir. Es un alma sensible que ha hecho del baile su particular forma de expresión, uniendo intima e indisolublemente técnica, estilo, emoción y expresión dancística.",
    image: "/images/obras/MercedesRuiz.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "8",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Leonor Leal",
    description:
      "Bailaora singular nacida en Jerez de la Frontera con una formación sólida en Danza Clásica y Española, encontró en el Flamenco el vehículo propicio para desarrollar sus inquietudes. Su versatilidad le permite adaptarse a contextos muy diversos y afrontar retos que le abren puertas para seguir creciendo como artista.",
    image: "/images/obras/LeonorLeal.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "9",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Juana La Del Pipa",
    description:
      "Juana La Del Pipa (Juana Fernández de los Reyes), cantaora y bailaora gitana, es de una de las puras  razas de artistas del mundo del mejor arte del cante y el baile flamenco, nacida en Jerez de la Frontera (Cádiz). Es la menor de las hijas de Tía Juana la del Pipa.",
    image: "/images/obras/JuanaLaDelPipa.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "10",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Paula Sierra",
    description:
      "Paula Sierra (San Fernando) es bailaora de flamenco que viene a defender el baile flamenco más puro. Antonio Canales la descubrió en unas clases magistrales y comenzó su total dedicación a lo que amaba, bailar flamenco, destacando su chispa, su fuerza, su flamencura, esa pasión que hace del flamenco un arte.",
    image: "/images/obras/PaulaSierra.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "11",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Manuela Carpio",
    description:
      "Manuela Moneo Carpio (Jerez de la Frontera), bailaora de puro flamenco, más conocida internacionalmente en el mundo de la historia del arte del baile flamenco con su propio nombre artístico de Manuela Carpio. En sus apellidos arraigan dos familias sin las que no se entendería el flamenco actual.",
    image: "/images/obras/ManuelaCarpio.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "12",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Dolores Agujetas",
    description: `Dolores de los Santos Bermúdez (Jerez de la Frontera), conocida artísticamente como "Dolores Agujetas", es una cantaora de flamenco gitana nacida en Jerez de la Frontera. Posee una voz rota y profunda, fiel a sus raíces jerezanas.`,
    image: "/images/obras/DoloresAgujetas.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "13",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "La Tia Yoya",
    description: `Antonia Reyes Valencia, conocida como Tía Yoya, hija de Tía Juana la del Pipa, es una figura legendaria del flamenco nacida en 1939 y originaria del emblemático Barrio de Santiago en Jerez de la Frontera. Aunque se dedicó a las labores del hogar durante gran parte de su vida, es considerada un auténtico icono e institución del baile por bulerías natural y casero.`,
    image: "/images/obras/LaTiaYoya.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "14",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "La Macanita",
    description: `Tomasa Guerrero Carrasco (Jerez de la Frontera), más conocida como "La Macanita", despunta en el cante desde niña. Cantaora larga y llena de jondura, temple y pellizco, La Macanita es heredera y continuadora de voces cantaoras como La Paquera, Fernanda de Utrera y La Perla de Cádiz. Artista de amplio repertorio, La Macanita emociona con su inconfundible eco por soleá y brilla por bulerías.`,
    image: "/images/obras/LaMacanita.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
  {
    id: "15",
    type: "Fotografía Ilustrada",
    project: "Flamencas Ilustradas",
    title: "Adela Campallo",
    description:
      "Adela Campallo (Sevilla), es una bailarina y desde pequeña ha estado inmersa en el mundo del flamenco. Su padrino, su tío y su hermano Rafael son guitarristas, y su madre, aunque nunca se haya dedicado a ello profesionalmente, siempre ha cantado en casa, así que Adela ha respirado flamenco desde que era una niña.",
    image: "/images/obras/AdelaCampallo.webp",
    year: 2023,
    isForSale: true,
    resolution: "1600x1200",
  },
];
